tunnel: <TUNNEL_ID>  # ganti dengan Tunnel ID dari cloudflared
credentials-file: ~/.cloudflared/<TUNNEL_ID>.json

ingress:
  - hostname: myflask.trycloudflare.com
    service: http://localhost:5000
  - service: http_status:404
