tunnel: <TUNNEL_ID>                # Ganti <TUNNEL_ID> dengan Tunnel ID yang kamu dapat
credentials-file: ~/.cloudflared/<TUNNEL_ID>.json

ingress:
  - hostname: orionai.trycloudflare.com
    service: http://localhost:5000
  - service: http_status:404
