# simpan TUNNEL_ID ke variabel
TID="d4153116-9a7e-4f91-a06c-b5aac97809ba"

# buat folder config jika belum ada
mkdir -p /root/.cloudflared

# buat config.yml
cat > /root/cloudflare/config.yml <<YML
tunnel: $TID
credentials-file: /root/.cloudflared/$TID.json

ingress:
  - hostname: orionai.trycloudflare.com
    service: http://localhost:5000
  - service: http_status:404
YML

# cek apakah file JSON tunnel ada
ls -l /root/.cloudflared/
